### PR TITLE
Remove C2MD and GCM Message API support

### PR DESCRIPTION
**Pull request by pmeulen**
Both these APIs are no longer offfered by Google. Use Firebase Cloud Messaging (FCM) instead.
C2DM was officially deprecated on June 26, 2012, and was shut down completely as of July 30, 2015 (https://developers.google.com/android/c2dm)
On April 10, 2018, Google deprecated GCM. The GCM server and client APIs were removed on May 29, 2019 (https://developers.google.com/cloud-messaging)

Related PR to remove GCM from Stepup-tiqr: https://github.com/OpenConext/Stepup-tiqr/pull/144

Update: Removed references to GCM and C2DM in code, tests and comments that were missed (thanks @MKodde !). Fixed comments and two bugs in GCM and APNS implementations while I was there too.

### CODE REVIEW

**Comment by MKodde** [comment]
Grepping on `c2dm` did yield some search results. `C2DM` seems intermingled with the `APNS` implementation. But some other results might need some attention?

```
Usage in comments

tiqr-server-libphp/library/tiqr/Tiqr/Service.php
   * - c2dm.username: The username for your android c2dm account
   * - c2dm.password: The password for your android c2dm account
   * - c2dm.application: The application identifier for your android 
   * @param String $notificationType    Notification type, e.g. APNS, C2DM, GCM, (SMS?)

library/tiqr/Tiqr/Message/APNS.php
   * Factory method for returning a C2DM service instance for the given 
   * @return Zend_Service_Google_C2dm service instance

Usage in string constants

tiqr-server-libphp/library/tiqr/tests/Tiqr_ServiceTest.php
   'c2dm.username' => 'test_c2dm_username',
   'c2dm.password' => 'test_c2dm_password',
   'c2dm.application' => 'org.example.authenticator.test',

library/tiqr/Tiqr/Service.php
   if ($notificationType == 'APNS' || $notificationType == 'C2DM' || $notificationType == 'GCM' || $notificationType == 'FCM') {
```

**Review by MKodde — APPROVED** [review]
That looks much better!

**Review by VadimSchmitz — CHANGES_REQUESTED** [review]
There are still mentions of G2MD and GCM in the README.md. Would it be possible to update               this?

**Comment by pmeulen** [comment]
Good point @VadimSchmitz
Rewrote the Zend dependency part, as LDAP has gone as well

**Review by VadimSchmitz — APPROVED** [review]
good job.

**Pull request merged**
